### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by love-bk** [androidthings/sample-videoRTC#2]
```
    factory = new PeerConnectionFactory(options, encoderFactory, decoderFactory);
```
error: 对于PeerConnectionFactory(Options,VideoEncoderFactory,VideoDecoderFactory), Can't find a suitable constructor

constructor
PeerConnectionFactory.PeerConnectionFactory(Options,AudioDeviceModule,VideoEncoderFactory,VideoDecoderFactory,AudioProcessingFactory,FecControllerFactoryFactoryInterface)
Not applicable (actual parameter list and formal parameter list are different in length)

constructor
 PeerConnectionFactory.PeerConnectionFactory(long)Not applicable (actual parameter list and formal parameter list are different in length)

**Comment by devunwired** [comment]
Corrected with the latest commit
